import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav className="navbar">
          <Link href="/" className="link">
            홈
          </Link>
          <Link href="/list" className="link">
            LIST
          </Link>
          <Link href="/cart" className="link">
            CART
          </Link>
        </nav>
        {children}
      </body>
    </html>
  );
}
